// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Records_screen_init(void)
{
    ui_Records = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Records, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Records_Roller4 = lv_roller_create(ui_Records);
    lv_roller_set_options(ui_Records_Roller4, "\nAUS00011111\nAUS0222222\nAUS0001122\nAUS0000555\nAUS0006661\nAUS0123456",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Records_Roller4, lv_pct(100));
    lv_obj_set_height(ui_Records_Roller4, lv_pct(90));
    lv_obj_set_x(ui_Records_Roller4, 0);
    lv_obj_set_y(ui_Records_Roller4, lv_pct(5));
    lv_obj_set_align(ui_Records_Roller4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Records_Roller4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label4 = lv_label_create(ui_Records);
    lv_obj_set_width(ui_Records_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label4, 0);
    lv_obj_set_y(ui_Records_Label4, -145);
    lv_obj_set_align(ui_Records_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label4, "Records ...");
    lv_obj_add_state(ui_Records_Label4, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_Records_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Button4 = lv_btn_create(ui_Records);
    lv_obj_set_width(ui_Records_Button4, 34);
    lv_obj_set_height(ui_Records_Button4, 24);
    lv_obj_set_x(ui_Records_Button4, 65);
    lv_obj_set_y(ui_Records_Button4, -144);
    lv_obj_set_align(ui_Records_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Records_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Records_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Records_Button4, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_Records_Button4, ui_event_Records_Button4, LV_EVENT_ALL, NULL);

}
